controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile2 = sprites.createProjectileFromSprite(img`
        ........................bbbbbbbbbbbbbbbbbbb..................................
        ......................bbbaaaaaaaaaaaaaaaabbbbb...............................
        .....................bbaaaaaaaaaaaaaaaaaaaaaabbb......bbc....................
        ....................bbaaaaaaaaaaaaaaaaaaaaaaaaabbb..cbbcc....................
        ...................bbaaaaaaaaaaaaaaaaaaaaaaaaaaaabccbbccc....................
        ...................baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccc.....................
        ..................bbaaabaaaaaaaaabaaaaaaaaaaaaaaaaaacccc.....................
        ..................baaaabaaaaaaaaabbaaaaaaaaaaaaaaaaaaccc.....................
        ..................caaaaaaaaaaaaaaaaaaaaaaaabcccaaaaaaacc.....ccc.............
        ..................caaaaabaaaaaaaaaaaaaaaaaaccc1caaaaaaaccccccbbc.............
        ..................caaaabaaaaaaaabaaaaaaaaaaacbbcaaaaaaaacccbbbcc.............
        ..................caaabddaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaccbccc..............
        ..................caaabadaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaccccc..............
        ...................caaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccc..............
        ...................caaaaaaaaaaaaaaaabaabaaaaaaabbaaaaaaaaaaacc...............
        ....................caaaaaaaaaaaaaaaaaabaaaaaaabaaaaaaaaaaaacc...............
        ....................caaaaaaaaaaaaaaaaaaaabaaaabaaaaaaaaaaaaaac...............
        .....................caaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccbbc.........
        ......................caaaaaaaabaaaaaaaabaaaaaaaaaaaaaaaaaaaaaccbbcc.........
        ......................ccaaaaaaaaaabaaaaaaaaabaaaaaaaaaaaaaaaaacccccc.........
        .......................ccaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaccccc..........
        ...............3........ccbaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccc..........
        .........................cbaaaaaabaaaaaaabaaaaaaaaaaaaaaaaaaaaacccc..........
        .........................caaaaaaabaabaaabaaaaaaaaaaaaaaaaaaaaaaaccc..........
        .................cccc....caaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaacc...........
        ................caaacc...caaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaacc...........
        ................caaaac...caaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaccc.........
        ..............cccaaaaac..cbaaaaaaaacaaaaaaaaaaaaaaccccaaaaaaaaaaacccccc......
        .............caaaaaaaaac..caaaabbabaaaaaaaaaaaaaaacaaccccaaaaaaaacccccc......
        .............caaaaaaaaacc..cabbaaaaaabaaaaaaaaaaaacbaaaaccccaaaaaccccc.......
        .............caaaaaabbbac..caaaaaaaaaaaaaaaaaaaccccbbaabbaabcaaaabccc........
        ..............aaaaaabaaaccccaaaaaaaaaaaaaaaaaaacaaccbbbbaaaabcaaaacc.........
        .............caaaaabaaabaaaaaaaaaaaaaaaaaaaaaaabbaaaaabaaaaaaacaaac..........
        ...........ccbbbaaabbbbaaaaaaaaaaaaaaaaaaaaaaaaabbaaaabccbbaaaccaacc.........
        ...........caaabbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabcaaaaaaabbaaacaaacc........
        ...........caaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacaaaaabbbbaaacbaaac........
        ............cbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccaaabbaaaaaaabbbaac.......
        .............cbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacaaabaaaaaaaaabbbacc......
        ..............cccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccaaabbbaaaaaaaaaaac......
        ................ccaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaacaaaaaaaaaaaaaaaaac......
        .................caaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaaaaaaaac......
        ..cc.............ccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacaaaaaaaaaaaaaaaac......
        ..cabb............ccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaaaaaaac......
        ..caab.............ccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacaaaaaaaaaaaaaacc......
        ..cbabb.............caaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaaaaacc......
        ..cbaab..............caaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccaaaaaaaaaacc.......
        ..cbaab..............caaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccaaaaaaacc........
        ..caaab..............caaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccccccccc........
        .cbaaabb.............caaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccc.......
        .cbaaabb............ccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccc......
        .caaaaab...........cccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccc.......
        cbaaaaab..........cccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacc........
        cbaaaaab........bccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac.........
        caaaaaaabb....bbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac.........
        caaaaaaaabbbbbbaaaacaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac.........
        caaaaaaaaaaaaaaaaacaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac.........
        caaaaaaaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacc........
        caaaaaaaaaaaaaaaacaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac........
        caaaaaaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacc.......
        ccaaaaaaaaaaaaaacaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac.......
        .caaaaaaaaaaaaaacaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac.......
        .ccaaaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacc......
        ..ccaaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac......
        ...ccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac......
        ....cccaaaaaaaacaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac......
        ......cccaaaaaccaaaaaaaaaaaaaaaaaccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaac......
        ........cccccccaaaaaaaaaaaaaaaaaccc........ccccaaaaaaaaaaaaaaaaaaaaaaacc.....
        ............cccaaaaaaaaaaaaaaaccc.............cccaaaaaaaaaaaaaaaaaaaaaccc....
        .............caaaaaaaaaaaaaaccc..................ccaaaaaaaaaaaaaaaaaaaccc....
        ...........ccaaaccaaaaaaaccccc....................ccaaaaaaaaaaaaaaaaaaaac....
        ..........ccaaaccaaaaacaacc........................cccaaaaaaaaaaaaaaaaaacc...
        ..........ccaaacaaaccccaac...........................ccccccaaaaaaaaaaaccaacc.
        ..........ccccccaacccccacc...............................ccaaaaaaccaaaaccaacc
        ...............cac.....ccc................................cccccaaaccaaaacaacc
        ...............cc...........................................ccccaaaccccaccccc
        ...............................................................ccccc..ccc....
        `, Boba_fett, 200, 0)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . 4 4 . . . . . . . 
        4 . . . . 4 4 4 5 4 . . . . . . 
        . 4 . . 4 4 5 5 5 5 4 . . . 4 . 
        . . . . 4 4 5 2 2 5 4 . . 4 . . 
        . . . . 4 4 4 5 2 5 4 4 . . . . 
        . . . 4 5 5 5 5 2 2 5 4 . . . . 
        . . . 4 5 2 4 2 2 5 4 4 . . . . 
        . . . 4 4 5 2 2 4 5 5 4 . . . . 
        . . . 4 4 5 2 2 5 5 4 . . . . . 
        . . . 4 4 5 5 5 5 4 4 . . . . . 
        . . . . 4 4 4 4 4 . . . . . . . 
        . . . . . . . . . . 4 . 4 3 . . 
        . . . 4 . . . . . . . 4 . . . . 
        . . . . . . . . . . . . . . . . 
        `, Boba_fett, 200, 0)
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    otherSprite.destroy()
    scene.cameraShake(4, 500)
    info.changeLifeBy(-1)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    Boba_fett.destroy(effects.fire, 500)
    info.changeScoreBy(100)
})
let mederer: Sprite = null
let projectile: Sprite = null
let projectile2: Sprite = null
let Boba_fett: Sprite = null
Boba_fett = sprites.create(img`
    ....................
    .....ff.............
    ....f1f.............
    ....f1fffff.........
    ....f6f7777f........
    ....f1222222f.f.fff.
    ...ff12ffffff.fff...
    ..f6f77222f2f.ffff..
    ..f6f77722f2ffdedef.
    ..ff5ff772f2f5defef.
    ..f5555fffff55ffff..
    .fddf5777d775f......
    .fdf.f77d7d7f.......
    .fdffffd777df.......
    .feeffd7777ff.......
    ..fffffffffddf......
    ..fdef254..fedf.....
    .feeef54....feef....
    .feeef554...feeef...
    .fffff54....fffff...
    `, SpriteKind.Player)
controller.moveSprite(Boba_fett, 100, 100)
Boba_fett.setStayInScreen(true)
info.setLife(3)
game.onUpdateInterval(1000, function () {
    mederer = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . f f . . 
        . . . . . . . . . . f f 9 9 f . 
        . . . . . . . . . f 1 1 1 f . . 
        . . . . . . . . . f 1 1 f . . . 
        . . . . . . . . f 1 1 1 f . . . 
        . . . . . . . . f 1 1 f . . . . 
        . . . . . . f f 1 1 1 f f f . . 
        . . . . f f 6 f 1 1 f 1 1 9 f f 
        . . . f 9 6 6 f 1 1 1 f f f . . 
        . . f 9 9 9 f 1 1 1 1 1 f f . . 
        . f f f f f f f f f f 1 1 9 f . 
        . . . . . f . . . . . f f 9 9 f 
        . . . . . . f . . . . . . f f . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Enemy)
    mederer.setVelocity(-100, 0)
    mederer.setPosition(160, randint(5, 115))
    mederer.setFlag(SpriteFlag.AutoDestroy, true)
})
